# Starship configuration
# This is a placeholder for your Starship prompt configuration.
# See https://starship.rs/config/ for more details.

"$schema" = 'https://starship.rs/config-schema.json'
add_newline = false

[aws]
disabled = true

[directory]
truncate_to_repo = true

# format = "$all"

# add_newline = false

# [character]
# success_symbol = "[âœ](bold green)"
# error_symbol = "[âœ—](bold red)"

# [git_branch]
# symbol = "ğŸŒ± "

# [git_status]
# conflicted = "ğŸ³"
# ahead = "ğŸğŸ’¨"
# behind = "ğŸ¢"
# diverged = "ğŸ¤¯"
# untracked = "ğŸ¤·â€â™€ï¸"
# staged = "ğŸ“"
# skipped = "â©"
# stashed = "ğŸ“¦"
# modified = "âœï¸"
# read_only = "ğŸ”’"
#
# [hostname]
# ssh_only = false
# format = "[$hostname](bold yellow)@"
